const constants = {
    IS_LOADING: 'IS_LOADING',
    IS_AUTHENTICATED: 'IS_AUTHENTICATED',
    IS_RUNNING: 'IS_RUNNING',
    SET_RUNNING_ENTRY: 'SET_RUNNING_ENTRY',
    SET_USER_DATA: 'SET_USER_DATA',
    SET_TIMER: 'SET_TIMER',
    LOADING_ERROR: 'LOADING_ERROR'
}

export default constants;