const constants = {
    IS_LOADING: 'IS_LOADING',
    IS_RUNNING: 'IS_RUNNING',
    IS_FETCHING: 'IS_FETCHING',
    IS_ONLINE: 'IS_ONLINE',
    IS_AUTHENTICATED: 'IS_AUTHENTICATED',
    SET_RUNNING_ENTRY: 'SET_RUNNING_ENTRY',
    SET_DAYS_TO_SHOW_LENGTH: ' SET_DAYS_TO_SHOW_LENGTH',
    SET_RUNNING_ENTRY_DESCRIPTION: 'SET_RUNNING_ENTRY_DESCRIPTION',
    SET_USER_DATA: 'SET_USER_DATA',
    SET_SETTINGS: 'SET_SETTINGS',
    SET_ENTRIES: 'SET_ENTRIES',
    SET_MAPPED_ITEMS: 'SET_MAPPED_ITEMS',
    ADD_ENTRIES: 'ADD_ENTRIES',
    EDIT_ENTRIES: 'EDIT_ENTRIES',
    REMOVE_ENTRIES: 'REMOVE_ENTRIES',
    SET_TIMER: 'SET_TIMER',
    SET_BILLABLE: 'SET_BILLABLE',
    SET_PROJECT: 'SET_PROJECT',
    SET_WEEK_TIMER: 'SET_WEEK_TIMER',
    ALL_ENTRIES_FETCHED: `ALL_ENTRIES_FETCHED`,
    PAGE_ERROR: 'PAGE_ERROR'
}

export default constants;