enum global {
  GLOBAL_SET_IS_LOGGED_IN = "GLOBAL_SET_IS_LOGGED_IN",
  GLOBAL_INIT_AUTH = "GLOBAL_INIT_AUTH",
}

enum user {
  USER_GET_USER_DATA = "USER_GET_USER_DATA",
  USER_SET_USER_DATA = "USER_SET_USER_DATA",
  USER_SET_ENTRIES = "USER_SET_ENTRIES",
  USER_SET_PROJECTS = "USER_SET_PROJECTS",
}

export const types = { ...global, ...user };
