enum global {
  GLOBAL_SET_IS_LOGGED_IN = "GLOBAL_SET_IS_LOGGED_IN",
  GLOBAL_SET_IS_LOADING = "GLOBAL_SET_IS_LOADING",
  GLOBAL_INIT_AUTH = "GLOBAL_INIT_AUTH",
  GLOBAL_INIT_RE_AUTH = "GLOBAL_INIT_RE_AUTH",
  GLOBAL_INIT_LOGOUT = "GLOBAL_INIT_LOGOUT",
  GLOBAL_FETCH_ERROR = "GLOBAL_FETCH_ERROR",
}

enum user {
  USER_GET_USER_DATA = "USER_GET_USER_DATA",
  USER_SET_USER_DATA = "USER_SET_USER_DATA",
  USER_SET_ENTRIES = "USER_SET_ENTRIES",
  USER_SET_PROJECTS = "USER_SET_PROJECTS",
}

enum timer {
  TIMER_SET_IS_RUNNING = "TIMER_SET_IS_RUNNING",
  TIMER_SET_TIMER = "TIMER_SET_TIMER",
}

export const types = { ...global, ...user, ...timer };
